-- Uniserv OS — script de criação das tabelas (PostgreSQL)
--
-- Como usar:
--   1. Crie o banco:                  createdb uniserv_os
--   2. Rode este script:               psql -U usuario -d uniserv_os -f backend/src/database/schema.sql
--   3. Rode o seed (dados iniciais):   npm run seed --prefix backend

CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_completo" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "telefone" varchar,
  "senha_hash" varchar NOT NULL,
  "perfil" varchar NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "refresh_token" varchar,
  "data_cadastro" timestamp DEFAULT (now())
);
CREATE TABLE "cliente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "razao_social" varchar NOT NULL,
  "cpf_cnpj" varchar UNIQUE NOT NULL,
  "telefone" varchar,
  "email" varchar UNIQUE,
  "endereco" text,
  "contato_nome" varchar
);
CREATE TABLE "tecnico" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int UNIQUE NOT NULL,
  "regiao" varchar,
  "ativo" boolean NOT NULL DEFAULT true
);
CREATE TABLE "equipamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pat" varchar UNIQUE NOT NULL,
  "modelo" varchar NOT NULL,
  "marca" varchar,
  "localizacao" varchar,
  "status" varchar NOT NULL DEFAULT 'ativo',
  "cliente_id" int NOT NULL,
  "data_instalacao" date,
  "data_desinstalacao" date
);
CREATE TABLE "chamado" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar NOT NULL,
  "prioridade" varchar NOT NULL DEFAULT 'media',
  "categoria" varchar,
  "descricao" text NOT NULL,
  "status" varchar NOT NULL DEFAULT 'aberto',
  "origem" varchar NOT NULL,
  "data_abertura" timestamp DEFAULT (now()),
  "data_encerramento" timestamp,
  "cliente_id" int NOT NULL,
  "equipamento_id" int,
  "tecnico_id" int,
  "supervisor_id" int
);
CREATE TABLE "historico_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chamado_id" int NOT NULL,
  "status" varchar NOT NULL,
  "alterado_por" int,
  "observacao" text,
  "data_alteracao" timestamp DEFAULT (now())
);
CREATE TABLE "atendimento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chamado_id" int UNIQUE NOT NULL,
  "tecnico_id" int NOT NULL,
  "data_inicio" timestamp,
  "data_fim" timestamp,
  "descricao_acoes" text,
  "observacoes" text
);
CREATE TABLE "suprimento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "atendimento_id" int NOT NULL,
  "chamado_id" int NOT NULL,
  "nome_item" varchar NOT NULL,
  "quantidade" int NOT NULL DEFAULT 1,
  "data_uso" timestamp DEFAULT (now())
);
CREATE TABLE "ordem_servico" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_os" varchar UNIQUE NOT NULL,
  "chamado_id" int UNIQUE NOT NULL,
  "atendimento_id" int,
  "assinatura_digital" text,
  "data_geracao" timestamp DEFAULT (now())
);
CREATE TABLE "mensagem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chamado_id" int NOT NULL,
  "remetente_id" int NOT NULL,
  "conteudo" text NOT NULL,
  "data_envio" timestamp DEFAULT (now()),
  "lido" boolean NOT NULL DEFAULT false
);
CREATE TABLE "avaliacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chamado_id" int UNIQUE NOT NULL,
  "cliente_id" int NOT NULL,
  "nota" int NOT NULL,
  "comentario" text,
  "data_avaliacao" timestamp DEFAULT (now())
);
CREATE TABLE "notificacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "chamado_id" int,
  "tipo_evento" varchar NOT NULL,
  "mensagem" text NOT NULL,
  "lido" boolean NOT NULL DEFAULT false,
  "data_criacao" timestamp DEFAULT (now())
);
ALTER TABLE "cliente" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tecnico" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "equipamento" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chamado" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chamado" ADD FOREIGN KEY ("equipamento_id") REFERENCES "equipamento" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chamado" ADD FOREIGN KEY ("tecnico_id") REFERENCES "tecnico" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chamado" ADD FOREIGN KEY ("supervisor_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historico_status" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historico_status" ADD FOREIGN KEY ("alterado_por") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "atendimento" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "atendimento" ADD FOREIGN KEY ("tecnico_id") REFERENCES "tecnico" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "suprimento" ADD FOREIGN KEY ("atendimento_id") REFERENCES "atendimento" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "suprimento" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ordem_servico" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ordem_servico" ADD FOREIGN KEY ("atendimento_id") REFERENCES "atendimento" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mensagem" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mensagem" ADD FOREIGN KEY ("remetente_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "avaliacao" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "avaliacao" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notificacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notificacao" ADD FOREIGN KEY ("chamado_id") REFERENCES "chamado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
